"""empty message

Revision ID: 239e35a180de
Revises: 2cfb29e56fc2
Create Date: 2020-03-27 23:33:39.341614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '239e35a180de'
down_revision = '2cfb29e56fc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repair', sa.Column('is_available', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_repair_is_available'), 'repair', ['is_available'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repair_is_available'), table_name='repair')
    op.drop_column('repair', 'is_available')
    # ### end Alembic commands ###
