"""added img_path

Revision ID: 79246812ebda
Revises: c65c8ce26edf
Create Date: 2020-04-01 08:55:44.548583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79246812ebda'
down_revision = 'c65c8ce26edf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('img_url', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'img_url')
    # ### end Alembic commands ###
