"""Added timestamp

Revision ID: 857f88715abc
Revises: 239e35a180de
Create Date: 2020-03-28 19:09:26.772080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '857f88715abc'
down_revision = '239e35a180de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_device_timestamp'), 'device', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_timestamp'), table_name='device')
    op.drop_column('device', 'timestamp')
    # ### end Alembic commands ###
