"""Added type to device

Revision ID: ae3d354afd19
Revises: cdbbbbc18a68
Create Date: 2020-04-11 15:52:41.565035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae3d354afd19'
down_revision = 'cdbbbbc18a68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('type', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'type')
    # ### end Alembic commands ###
