"""Trying to fix timestamp

Revision ID: c65c8ce26edf
Revises: 857f88715abc
Create Date: 2020-03-31 13:17:16.782243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c65c8ce26edf'
down_revision = '857f88715abc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repair', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_repair_timestamp'), 'repair', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repair_timestamp'), table_name='repair')
    op.drop_column('repair', 'timestamp')
    # ### end Alembic commands ###
